### ISSUE TITLE
synchronize Todoist tasks to workflowy？

### ISSUE THREAD

**Issue by yoghurtdewdew** [xiexed/todoist-yt-sync#1]
Hello, your project looks great. May I ask if it is possible to synchronize Todoist tasks to workflowy? This is something I am looking forward to, but I am a bit confused and don't know how to configure these. I am not very familiar with the code aspect.

**Comment by xiexed** [comment]
Sorry, I am afraid this project is not applicable to wide public and it too tightly coupled to my own needs.  To configure it you will need to patch code with your todoist-id and get some oauth-keys, so if you are not ready to make some coding and deployment work then there is no way to use this project.

Also it actually doesn't sync "todoist to workflowy" in terms like putting tasks from todoist and make them workflowy records - such functionality is not supported.
